#!/usr/bin/env python3
"""
Convert existing general skills into a consolidated Routing Skill.
"""

import argparse
import shutil
import sys
from pathlib import Path

# update_index.py is in the same directory
import update_index

ROUTING_SKILL_TEMPLATE = """---
name: {skill_name}
description: Routing skill generated by routerize-skills.
---

# {skill_name}

This is a routing skill.

## Sub-Skills

This skill acts as a router for multiple sub-skills.
Refer to `sub-skills/INDEX.csv` to find the appropriate sub-skill.
"""


def parse_frontmatter(content: str) -> dict[str, str]:
    """Parse YAML frontmatter to extract name and description."""
    data = {"name": "", "description": ""}
    if not content.startswith("---"):
        return data
        
    parts = content.split("---", 2)
    if len(parts) >= 3:
        frontmatter = parts[1]
        for line in frontmatter.splitlines():
            line = line.strip()
            if line.startswith("name:"):
                data["name"] = line[5:].strip()
            elif line.startswith("description:"):
                # Simplified extraction, ignoring multiline YAML
                data["description"] = line[12:].strip()
    return data


def setup_target(target: Path, studio_scripts_dir: Path):
    """Initialize the routing skill structure."""
    target.mkdir(parents=True, exist_ok=True)
    (target / "sub-skills").mkdir(exist_ok=True)
    (target / "scripts").mkdir(exist_ok=True)
    
    # Create SKILL.md
    skill_md = target / "SKILL.md"
    if not skill_md.exists():
        skill_md.write_text(ROUTING_SKILL_TEMPLATE.format(skill_name=target.name), encoding="utf-8")
        
    # Init INDEX.csv
    update_index.init_index(target / "sub-skills" / "INDEX.csv")


def process_lite(target: Path, skill_paths: list[Path]):
    """Lite mode: move whole skill dir, rename SKILL.md to SUB-SKILL.md."""
    index_path = target / "sub-skills" / "INDEX.csv"
    
    for spath in skill_paths:
        if not spath.is_dir():
            print(f"Warning: {spath} is not a directory. Skipping.", file=sys.stderr)
            continue
            
        skill_name = spath.name
        dest_dir = target / "sub-skills" / skill_name
        
        # Read frontmatter before moving
        old_skill_md = spath / "SKILL.md"
        meta = {"name": skill_name, "description": ""}
        if old_skill_md.exists():
            content = old_skill_md.read_text(encoding="utf-8")
            parsed = parse_frontmatter(content)
            meta["name"] = parsed.get("name") or skill_name
            meta["description"] = parsed.get("description", "")
            
        # Move directory
        if dest_dir.exists():
            print(f"Warning: Destination {dest_dir} already exists. Skipping.", file=sys.stderr)
            continue
            
        shutil.move(str(spath), str(dest_dir))
        
        # Rename SKILL.md to SUB-SKILL.md
        new_skill_md = dest_dir / "SKILL.md"
        if new_skill_md.exists():
            new_skill_md.rename(dest_dir / "SUB-SKILL.md")
            
        # Update index
        update_index.update_index(index_path, {
            "name": f"{skill_name}/SUB-SKILL.md",
            "overview": meta["description"],
            "keywords": meta["name"],
            "trigger": meta["name"],
            "exclusion": ""
        })
        print(f"Routerized (lite): {skill_name}")


def process_full(target: Path, skill_paths: list[Path]):
    """Full mode: flatten to target/sub-skills/<skill-name>.md, merge assets."""
    index_path = target / "sub-skills" / "INDEX.csv"
    
    # Resource dirs that might contain files
    resource_dirs = ["assets", "scripts", "references", "prompts"]
    
    for spath in skill_paths:
        if not spath.is_dir():
            print(f"Warning: {spath} is not a directory. Skipping.", file=sys.stderr)
            continue
            
        skill_name = spath.name
        old_skill_md = spath / "SKILL.md"
        new_skill_md = target / "sub-skills" / f"{skill_name}.md"
        
        meta = {"name": skill_name, "description": ""}
        if not old_skill_md.exists():
            print(f"Warning: No SKILL.md found in {spath}. Skipping.", file=sys.stderr)
            continue
            
        content = old_skill_md.read_text(encoding="utf-8")
        parsed = parse_frontmatter(content)
        meta["name"] = parsed.get("name") or skill_name
        meta["description"] = parsed.get("description", "")
        
        # Move and resolve resources
        path_replacements = {}  # { "assets/img.png" : "assets/img-skill_name.png" }
        
        for rdir in resource_dirs:
            src_rdir = spath / rdir
            if not src_rdir.exists() or not src_rdir.is_dir():
                continue
                
            dst_rdir = target / rdir
            dst_rdir.mkdir(exist_ok=True)
            
            for item in src_rdir.iterdir():
                if not item.is_file():
                    continue
                    
                dst_item = dst_rdir / item.name
                if dst_item.exists():
                    # Handle collision
                    new_name = f"{item.stem}-{skill_name}{item.suffix}"
                    dst_item = dst_rdir / new_name
                    
                shutil.move(str(item), str(dst_item))
                
                # We assume the markdown referenced it as `rdir/item.name` or similar
                # We should replace occurrences in the markdown content
                path_replacements[f"{rdir}/{item.name}"] = f"../{rdir}/{dst_item.name}"
                
        # Rewrite markdown paths
        for old_path, new_path in path_replacements.items():
            content = content.replace(old_path, new_path)
            
        # Write new flattened skill md
        new_skill_md.write_text(content, encoding="utf-8")
        
        # Clean up old dir if empty
        shutil.rmtree(str(spath), ignore_errors=True)
        
        # Update index
        update_index.update_index(index_path, {
            "name": f"{skill_name}.md",
            "overview": meta["description"],
            "keywords": meta["name"],
            "trigger": meta["name"],
            "exclusion": ""
        })
        print(f"Routerized (full): {skill_name}")


def main():
    parser = argparse.ArgumentParser(description="Convert skills to a routing skill.")
    parser.add_argument("--mode", choices=["lite", "full"], default="lite", help="Mode of conversion")
    parser.add_argument("--target", required=True, type=Path, help="Target routing skill directory")
    parser.add_argument("skills", nargs="+", type=Path, help="Directories of skills to consolidate")
    
    args = parser.parse_args()
    
    studio_scripts_dir = Path(__file__).parent.resolve()
    
    setup_target(args.target, studio_scripts_dir)
    
    if args.mode == "lite":
        process_lite(args.target, args.skills)
    else:
        process_full(args.target, args.skills)


if __name__ == "__main__":
    main()
