from .adr import (
    ADR_ARCHIVE_INDEX_TEMPLATE,
    ADR_DOCUMENT_TEMPLATE,
    ADR_INDEX_TEMPLATE,
    ADR_README_TEMPLATE,
)
from .prd import (
    PRD_ARCHIVE_INDEX_TEMPLATE,
    PRD_DOCUMENT_TEMPLATE,
    PRD_INDEX_TEMPLATE,
    PRD_README_TEMPLATE,
)
from .spec import (
    SPEC_ARCHIVE_INDEX_TEMPLATE,
    SPEC_DOCUMENT_TEMPLATE,
    SPEC_INDEX_TEMPLATE,
    SPEC_README_TEMPLATE,
)

__all__ = [
    "ADR_INDEX_TEMPLATE",
    "ADR_README_TEMPLATE",
    "ADR_ARCHIVE_INDEX_TEMPLATE",
    "ADR_DOCUMENT_TEMPLATE",
    "PRD_INDEX_TEMPLATE",
    "PRD_README_TEMPLATE",
    "PRD_ARCHIVE_INDEX_TEMPLATE",
    "PRD_DOCUMENT_TEMPLATE",
    "SPEC_INDEX_TEMPLATE",
    "SPEC_README_TEMPLATE",
    "SPEC_ARCHIVE_INDEX_TEMPLATE",
    "SPEC_DOCUMENT_TEMPLATE",
]
